sudo: required
language: node_js
env:
  global:
  - REDIS_PORT_6379_TCP_ADDR=localhost
  - REDIS_PORT_6379_TCP_PORT=6379
node_js:
- '8'
- '9'
services:
- docker
before_install:
- docker run -p 6379:6379 -d --name tree_redis redis:3.0.7-alpine
- docker run -p 80:7000 -d --name httpbin kennethreitz/httpbin
- docker run -p 8500:8500 -d --name tree_consul consul
script: nyc npm run test && nyc report --reporter=text-lcov | coveralls
deploy:
  - provider: npm
    email: thiago@cruxframework.org
    api_key:
      secure: GTr1MpuxsDzKGJmkpLsRkPB6pCqM214RDp5N9orQ3pbRt7irQxvjZddLvJ+45beHY4+AvICM5rAchkAj7oW+tPSelFWTAOMZ36vLTDl1wbTIaD/bgwfOrFgVXyYWz6yRFrmqY7t3NuZBb0683k1SNNsLembz9vU5jo6S7wc/qjpxMYoZvjnSzH3GBn/c40BNc9LXXpn7k37in5Z7qRUYWUx8Z6aK1kuQl6bxuwVYSF/TdtxTVT+rHiNPHaNstgh2yA/XtdihM1H22ZJBTIvmTzoT1LmfKvkG6SKGb33GOTUDdQhgA3B3mXC+rwpfbjzFmWCC6DfKQXdv2Dtx4fVcsd1NNZmUEavxtGIqFlYRENOi1sqs6NRc8vXXPkitkmVtpcM6483cFSyR41cJ1ro3Xa5CeUOWKNI5F3+PuXFDti5cHvEgwVNHE3RAwKKGICZffsAgp7ywi/ne3leV78Y/M623DH+aPwbXBCddUHPx2B81ZMUj+cMof4HNzcl3VqE4vHJYqQo2CLcBwiac286LgxYas9v7N/wBE/dNgHNklGF/Ve4et00Wj0qQS3kUtXaoBS02XslvwoIPXYLErFP++jyLhLUzVrIabnUYOOXzdGIEOMbOjfLwRTOfGUn7z3GXqzpZMQ7tkMzfOlC9AXUFPwvbrk8uimHfkPrL10uymsg=
    skip_cleanup: true
    on:
      tags: true
      repo: Leanty/tree-gateway
  - provider: script
    skip_cleanup: true
    script: ./deploy-docker.sh
    on:
      tags: true
      repo: Leanty/tree-gateway
